"""Generate Homio Lovelace YAML from config entry options + room subentries."""
from __future__ import annotations

import logging
import re
import shutil
from pathlib import Path
from typing import Any

import yaml

from homeassistant.config_entries import ConfigEntry, ConfigSubentry
from homeassistant.core import HomeAssistant
from homeassistant.util import slugify as ha_slugify

from .const import (
    CONF_DEVICE_ENTITY,
    CONF_DEVICE_ICON,
    CONF_DEVICES,
    CONF_DISPLAY_NAME,
    CONF_HUMID_SENSOR,
    CONF_IMAGE,
    CONF_IMAGE_POSITION,
    CONF_LOGO_HOME_ROOM,
    CONF_LOGO_NAME,
    CONF_MOTION_SENSOR,
    CONF_NAV_NAME,
    CONF_NAV_ORDER,
    CONF_SHOW_HUMID,
    CONF_SHOW_IN_NAVIGATION,
    CONF_SHOW_MOTION,
    CONF_SHOW_TEMP,
    CONF_SLUG,
    CONF_TEMP_SENSOR,
    DEFAULT_DEVICE_ICON,
    DEFAULT_IMAGE_POSITION,
    DEFAULT_LOGO_NAME,
    DOMAIN,
    DOMAIN_ICON_MAP,
    SUBENTRY_TYPE_ROOM,
    USER_GENERATED_DIR,
    USER_HOMIO_DIR,
    USER_LAYOUT_DIR,
    USER_NAVIGATION_FILE,
    USER_SECTIONS_FILE,
)

_LOGGER = logging.getLogger(__name__)

_GENERATED_HEADER = (
    "# GENERATED by Homio Dashboard — edit via Settings → Devices & Services → Homio.\n"
    "# Manual edits will be overwritten on reload.\n"
)


def layout_dir(hass: HomeAssistant) -> Path:
    """Return /config/homio/layout."""
    return Path(hass.config.path(USER_HOMIO_DIR)) / USER_LAYOUT_DIR


def sections_path(hass: HomeAssistant) -> Path:
    """Return path to generated sections.yaml."""
    return layout_dir(hass) / USER_SECTIONS_FILE


def navigation_path(hass: HomeAssistant) -> Path:
    """Return path to generated navigation.yaml."""
    return layout_dir(hass) / USER_NAVIGATION_FILE


def generated_root(hass: HomeAssistant) -> Path:
    """Return /config/homio/layout/_generated."""
    return layout_dir(hass) / USER_GENERATED_DIR


def icon_for_entity(entity_id: str) -> str | None:
    """Return default Homio icon stem for an entity domain."""
    domain = entity_id.split(".", 1)[0]
    if domain in DOMAIN_ICON_MAP:
        return DOMAIN_ICON_MAP[domain]
    return DEFAULT_DEVICE_ICON


def card_template_for_entity(entity_id: str) -> str:
    """Return button-card template name for an entity."""
    domain = entity_id.split(".", 1)[0]
    if domain == "climate":
        return "homio_thermostat"
    if domain == "light":
        return "homio_light"
    return "homio_entity"


def room_slug(nav_name: str) -> str:
    """Infer Homio view path slug from a nav name."""
    slug = ha_slugify(nav_name.strip())
    return slug or "room"


def merge_devices(
    entity_ids: list[str],
    previous: list[dict[str, Any]] | None,
) -> list[dict[str, Any]]:
    """Build ordered device dicts; preserve icons; auto-map new entities."""
    prev_by_entity = {
        str(item.get(CONF_DEVICE_ENTITY)): item
        for item in (previous or [])
        if isinstance(item, dict) and item.get(CONF_DEVICE_ENTITY)
    }
    result: list[dict[str, Any]] = []
    for entity_id in entity_ids:
        if not entity_id:
            continue
        if entity_id in prev_by_entity:
            prev = prev_by_entity[entity_id]
            icon = prev.get(CONF_DEVICE_ICON)
            result.append({CONF_DEVICE_ENTITY: entity_id, CONF_DEVICE_ICON: icon})
        else:
            result.append(
                {
                    CONF_DEVICE_ENTITY: entity_id,
                    CONF_DEVICE_ICON: icon_for_entity(entity_id),
                }
            )
    return result


def room_subentries(entry: ConfigEntry) -> list[ConfigSubentry]:
    """Return room subentries for the Homio config entry."""
    return [
        sub
        for sub in entry.subentries.values()
        if sub.subentry_type == SUBENTRY_TYPE_ROOM
    ]


def ordered_rooms(entry: ConfigEntry) -> list[dict[str, Any]]:
    """Return room data dicts sorted for generation (nav order first)."""
    rooms = []
    for sub in room_subentries(entry):
        data = dict(sub.data)
        data.setdefault(CONF_SLUG, room_slug(str(data.get(CONF_NAV_NAME, sub.title))))
        data.setdefault(CONF_NAV_NAME, sub.title)
        rooms.append(data)

    by_slug = {r[CONF_SLUG]: r for r in rooms}
    nav_order = list(entry.options.get(CONF_NAV_ORDER, []))
    ordered: list[dict[str, Any]] = []
    seen: set[str] = set()
    for slug in nav_order:
        if slug in by_slug and slug not in seen:
            ordered.append(by_slug[slug])
            seen.add(slug)
    for room in rooms:
        slug = room[CONF_SLUG]
        if slug not in seen:
            ordered.append(room)
            seen.add(slug)
    return ordered


def _yaml_scalar(value: Any) -> str:
    """Format a YAML scalar."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    if re.search(r'[:#\[\]{}\n,"\']', text) or text == "":
        return yaml.dump(text, default_style="'").strip()
    return text


def _indent(text: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line else line for line in text.splitlines())


def _friendly_name(hass: HomeAssistant, entity_id: str) -> str:
    state = hass.states.get(entity_id)
    if state and state.attributes.get("friendly_name"):
        return str(state.attributes["friendly_name"])
    if "." in entity_id:
        return entity_id.split(".", 1)[1].replace("_", " ").title()
    return entity_id


def _device_card_yaml(hass: HomeAssistant, device: dict[str, Any]) -> str:
    entity_id = str(device[CONF_DEVICE_ENTITY])
    template = card_template_for_entity(entity_id)
    name = _friendly_name(hass, entity_id)
    icon = device.get(CONF_DEVICE_ICON)
    lines = [
        "- type: custom:button-card",
        "  template:",
        f"    - {template}",
        f"  entity: {entity_id}",
        f"  name: {_yaml_scalar(name)}",
    ]
    if template != "homio_thermostat" and icon:
        lines.extend(
            [
                "  variables:",
                f"    icon: {_yaml_scalar(icon)}",
            ]
        )
    return "\n".join(lines)


def _room_view_yaml(hass: HomeAssistant, room: dict[str, Any], includes_abs: str) -> str:
    slug = room[CONF_SLUG]
    nav_name = room.get(CONF_NAV_NAME, slug)
    display = room.get(CONF_DISPLAY_NAME) or nav_name
    image = room.get(CONF_IMAGE) or slug
    image_position = room.get(CONF_IMAGE_POSITION) or DEFAULT_IMAGE_POSITION
    show_temp = bool(room.get(CONF_SHOW_TEMP, False))
    show_humid = bool(room.get(CONF_SHOW_HUMID, False))
    show_motion = bool(room.get(CONF_SHOW_MOTION, False))
    temp_sensor = room.get(CONF_TEMP_SENSOR)
    humid_sensor = room.get(CONF_HUMID_SENSOR)
    motion_sensor = room.get(CONF_MOTION_SENSOR)
    devices = room.get(CONF_DEVICES) or []

    device_blocks = [
        _indent(_device_card_yaml(hass, d), 16)
        for d in devices
        if isinstance(d, dict) and d.get(CONF_DEVICE_ENTITY)
    ]
    if device_blocks:
        cards_yaml = "              cards:\n" + "\n".join(device_blocks)
    else:
        cards_yaml = "              cards: []"

    return f"""  - type: custom:grid-layout
    title: {_yaml_scalar(nav_name)}
    path: {slug}
    theme: homio
    layout: !include {includes_abs}/homio_screen_layout.yaml
    cards:
      - type: custom:button-card
        template:
          - homio_room
        name: {_yaml_scalar(display)}
        variables:
          image: {_yaml_scalar(image)}
          image_position: {_yaml_scalar(image_position)}
          show_temp: {_yaml_scalar(show_temp)}
          show_humid: {_yaml_scalar(show_humid)}
          show_motion: {_yaml_scalar(show_motion)}
          motion_sensor: {_yaml_scalar(motion_sensor)}
          temp_sensor: {_yaml_scalar(temp_sensor)}
          humid_sensor: {_yaml_scalar(humid_sensor)}
        custom_fields:
          entities:
            card:
              type: custom:layout-card
              layout_type: custom:grid-layout
              layout: !include {includes_abs}/homio_entity_layout.yaml
{cards_yaml}
"""


def _navigation_yaml(rooms: list[dict[str, Any]]) -> str:
    blocks: list[str] = []
    for room in rooms:
        if not room.get(CONF_SHOW_IN_NAVIGATION, True):
            continue
        slug = room[CONF_SLUG]
        nav_name = room.get(CONF_NAV_NAME, slug)
        blocks.append(
            f"""- type: custom:button-card
  template:
    - homio_nav_button
  name: {_yaml_scalar(nav_name)}
  variables:
    path: /{DOMAIN}/{slug}
"""
        )
    return _GENERATED_HEADER + ("\n".join(blocks) if blocks else "# (no nav rooms)\n")


def _patch_logo_files(button_cards_dir: Path, logo_name: str, home_slug: str) -> None:
    """Overwrite logo templates with configured name and home path."""
    path = f"/{DOMAIN}/{home_slug}" if home_slug else f"/{DOMAIN}"
    logo_yaml = f"""homio_logo:
  template:
    - homio_default
  tap_action:
    action: navigate
    navigation_path: {path}
  name: {_yaml_scalar(logo_name)}
  styles:
    name:
      - color: var(--primary-text-color)
      - letter-spacing: 2px
      - font-size: 18px
      - font-weight: 700
      - text-transform: uppercase
      - justify-self: start
      - line-height: 18px
    card:
      - "--ha-card-background": transparent
      - background: none
      - background-color: transparent
      - box-shadow: none
      - border: none
      - pointer-events: all
      - height: 18px
      - min-height: 0
      - padding: 0
      - margin: 0
"""
    mobile_yaml = f"""homio_mobile_logo:
  name: {_yaml_scalar(logo_name)}
  tap_action:
    action: navigate
    navigation_path: {path}
  styles:
    name:
      - color: var(--primary-text-color)
      - letter-spacing: 2px
      - font-size: 18px
      - font-weight: 700
      - text-transform: uppercase
      - justify-self: start
      - line-height: 18px
    card:
      - "--ha-card-background": transparent
      - background: none
      - background-color: transparent
      - box-shadow: none
      - border: none
      - pointer-events: all
      - height: 18px
      - min-height: 0
      - padding: 0
      - margin: 0
"""
    base = button_cards_dir / "base"
    base.mkdir(parents=True, exist_ok=True)
    (base / "homio_logo.yaml").write_text(logo_yaml, encoding="utf-8")
    (base / "homio_mobile_logo.yaml").write_text(mobile_yaml, encoding="utf-8")


def _patch_navigation_include(includes_dir: Path, nav_file_abs: str) -> None:
    """Copy navigation shell and point list include at generated navigation.yaml."""
    integration_includes = (
        Path(__file__).parent / "dashboards" / "templates" / "includes"
    )
    includes_dir.mkdir(parents=True, exist_ok=True)
    for name in (
        "homio_screen_layout.yaml",
        "homio_entity_layout.yaml",
        "homio_navigation.yaml",
    ):
        src = integration_includes / name
        dest = includes_dir / name
        if not src.is_file():
            continue
        text = src.read_text(encoding="utf-8")
        if name == "homio_navigation.yaml":
            text = text.replace(
                "!include homio_navigation_list.yaml",
                f"!include {nav_file_abs}",
            )
        dest.write_text(text, encoding="utf-8")


def generate_dashboard(hass: HomeAssistant, entry: ConfigEntry) -> Path:
    """Write generated layout files and return sections.yaml path."""
    integration_dir = Path(__file__).parent
    layout = layout_dir(hass)
    gen = generated_root(hass)
    button_cards_dest = gen / "button_cards"
    includes_dest = gen / "includes"

    layout.mkdir(parents=True, exist_ok=True)

    # Fresh mirror of button-card templates each generate.
    src_cards = integration_dir / "dashboards" / "templates" / "button_cards"
    if button_cards_dest.exists():
        shutil.rmtree(button_cards_dest)
    shutil.copytree(src_cards, button_cards_dest)

    rooms = ordered_rooms(entry)
    options = entry.options
    logo_name = str(options.get(CONF_LOGO_NAME) or DEFAULT_LOGO_NAME)
    home_slug = str(options.get(CONF_LOGO_HOME_ROOM) or "")
    if not home_slug and rooms:
        home_slug = str(rooms[0].get(CONF_SLUG, ""))

    nav_abs = str(navigation_path(hass)).replace("\\", "/")
    includes_abs = str(includes_dest).replace("\\", "/")
    button_cards_abs = str(button_cards_dest).replace("\\", "/")

    _patch_navigation_include(includes_dest, nav_abs)
    _patch_logo_files(button_cards_dest, logo_name, home_slug)

    navigation_path(hass).write_text(_navigation_yaml(rooms), encoding="utf-8")

    views = "\n".join(_room_view_yaml(hass, room, includes_abs) for room in rooms)
    if not views.strip():
        views = """  - type: custom:grid-layout
    title: Home
    path: home
    theme: homio
    layout: !include {includes}/homio_screen_layout.yaml
    cards:
      - type: markdown
        content: >
          Configure Homio rooms under
          **Settings → Devices & Services → Homio → Add room**.
""".format(includes=includes_abs)

    sections = f"""{_GENERATED_HEADER}
kiosk_mode:
  hide_header: true

button_card_templates: !include_dir_merge_named {button_cards_abs}

views:
{views}
"""
    out = sections_path(hass)
    out.write_text(sections, encoding="utf-8")
    _LOGGER.info("Homio dashboard generated at %s (%s rooms)", out, len(rooms))
    return out


# --- Migration from bundled / legacy lovelace YAML ---------------------------------


class _IgnoreIncludeLoader(yaml.SafeLoader):
    """YAML loader that treats !include* as null so views still parse."""


def _ignore_include(loader: yaml.SafeLoader, node: yaml.Node) -> None:
    return None


_IgnoreIncludeLoader.add_constructor("!include", _ignore_include)
_IgnoreIncludeLoader.add_constructor("!include_dir_merge_named", _ignore_include)
_IgnoreIncludeLoader.add_constructor("!include_dir_named", _ignore_include)
_IgnoreIncludeLoader.add_constructor("!include_dir_list", _ignore_include)
_IgnoreIncludeLoader.add_constructor("!include_dir_merge_list", _ignore_include)


def parse_rooms_from_homio_yaml(path: Path) -> list[dict[str, Any]]:
    """Best-effort parse room configs from a Homio lovelace YAML file."""
    if not path.is_file():
        return []
    try:
        data = yaml.load(path.read_text(encoding="utf-8"), Loader=_IgnoreIncludeLoader)
    except Exception as err:  # noqa: BLE001
        _LOGGER.warning("Failed to parse Homio YAML at %s: %s", path, err)
        return []
    if not isinstance(data, dict):
        return []
    views = data.get("views") or []
    rooms: list[dict[str, Any]] = []
    for view in views:
        if not isinstance(view, dict):
            continue
        path_slug = view.get("path")
        title = view.get("title") or path_slug
        if not path_slug:
            continue
        cards = view.get("cards") or []
        room_card = next(
            (
                c
                for c in cards
                if isinstance(c, dict)
                and "homio_room" in (c.get("template") or [])
            ),
            None,
        )
        if not room_card:
            room_card = cards[0] if cards and isinstance(cards[0], dict) else {}
        variables = room_card.get("variables") or {}
        devices: list[dict[str, Any]] = []
        entities_card = (
            ((room_card.get("custom_fields") or {}).get("entities") or {}).get("card")
            or {}
        )
        for device_card in entities_card.get("cards") or []:
            if not isinstance(device_card, dict):
                continue
            entity_id = device_card.get("entity")
            if not entity_id:
                continue
            icon = (device_card.get("variables") or {}).get("icon")
            if icon is None:
                icon = icon_for_entity(str(entity_id))
            devices.append(
                {CONF_DEVICE_ENTITY: str(entity_id), CONF_DEVICE_ICON: icon}
            )
        rooms.append(
            {
                CONF_NAV_NAME: str(title),
                CONF_SLUG: str(path_slug),
                CONF_DISPLAY_NAME: room_card.get("name") or str(title),
                CONF_SHOW_IN_NAVIGATION: True,
                CONF_IMAGE: variables.get("image") or path_slug,
                CONF_IMAGE_POSITION: variables.get("image_position")
                or DEFAULT_IMAGE_POSITION,
                CONF_SHOW_TEMP: bool(variables.get("show_temp", False)),
                CONF_TEMP_SENSOR: variables.get("temp_sensor"),
                CONF_SHOW_HUMID: bool(variables.get("show_humid", False)),
                CONF_HUMID_SENSOR: variables.get("humid_sensor"),
                CONF_SHOW_MOTION: bool(variables.get("show_motion", False)),
                CONF_MOTION_SENSOR: variables.get("motion_sensor"),
                CONF_DEVICES: devices,
            }
        )
    return rooms


def parse_logo_from_templates(integration_dir: Path) -> tuple[str, str | None]:
    """Read logo name and home path from bundled logo templates."""
    logo_path = (
        integration_dir
        / "dashboards"
        / "templates"
        / "button_cards"
        / "base"
        / "homio_logo.yaml"
    )
    logo_name = DEFAULT_LOGO_NAME
    home_slug: str | None = None
    if logo_path.is_file():
        try:
            data = yaml.safe_load(logo_path.read_text(encoding="utf-8")) or {}
            logo = data.get("homio_logo") or {}
            if logo.get("name"):
                logo_name = str(logo["name"])
            nav = (logo.get("tap_action") or {}).get("navigation_path") or ""
            if isinstance(nav, str) and nav.startswith(f"/{DOMAIN}/"):
                home_slug = nav[len(f"/{DOMAIN}/") :].strip("/") or None
        except Exception as err:  # noqa: BLE001
            _LOGGER.debug("Could not parse logo template: %s", err)
    return logo_name, home_slug


def migrate_rooms_from_yaml(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Create room subentries from bundled/legacy YAML when none exist.

    Returns True if subentries were added.
    """
    if room_subentries(entry):
        return False

    integration_dir = Path(__file__).parent
    candidates = [
        integration_dir / "lovelace" / "homio.yaml",
        Path(hass.config.path("dashboards")) / "homio" / "homio.yaml",
    ]
    rooms: list[dict[str, Any]] = []
    for path in candidates:
        rooms = parse_rooms_from_homio_yaml(path)
        if rooms:
            _LOGGER.info("Migrating Homio rooms from %s", path)
            break

    logo_name, home_slug = parse_logo_from_templates(integration_dir)
    if not rooms:
        # Minimal seed so the UI is usable.
        rooms = [
            {
                CONF_NAV_NAME: "Living",
                CONF_SLUG: "living",
                CONF_DISPLAY_NAME: "Living Room",
                CONF_SHOW_IN_NAVIGATION: True,
                CONF_IMAGE: "lounge",
                CONF_IMAGE_POSITION: DEFAULT_IMAGE_POSITION,
                CONF_SHOW_TEMP: False,
                CONF_TEMP_SENSOR: None,
                CONF_SHOW_HUMID: False,
                CONF_HUMID_SENSOR: None,
                CONF_SHOW_MOTION: False,
                CONF_MOTION_SENSOR: None,
                CONF_DEVICES: [],
            }
        ]
        home_slug = home_slug or "living"

    nav_order = [r[CONF_SLUG] for r in rooms if r.get(CONF_SHOW_IN_NAVIGATION, True)]
    if not home_slug and nav_order:
        home_slug = nav_order[0]

    for room in rooms:
        slug = room[CONF_SLUG]
        hass.config_entries.async_add_subentry(
            entry,
            ConfigSubentry(
                data=room,
                subentry_type=SUBENTRY_TYPE_ROOM,
                title=str(room.get(CONF_NAV_NAME) or slug),
                unique_id=slug,
            ),
        )

    hass.config_entries.async_update_entry(
        entry,
        options={
            CONF_LOGO_NAME: logo_name,
            CONF_LOGO_HOME_ROOM: home_slug or "",
            CONF_NAV_ORDER: nav_order,
        },
    )
    return True
